version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    volumes:
      - ./:/var/www/html/
      - ../test:/var/www/html
    restart: always
